### ISSUE TITLE
Consistent headings in WAP

### ISSUE THREAD

**Issue by asirota** [NewPath-Consulting/Wild-Apricot-Press#109]
Let's set the headers for each part of the plugin settings the consistent to what's under WildApricot Press. 

Here's the settings links under WAP ![image](https://user-images.githubusercontent.com/458134/187073406-0c8b6463-18e9-433d-9b5e-29d29edbcb5a.jpeg)

Set header to "Authorization"
![image](https://user-images.githubusercontent.com/458134/187073383-eced732a-0798-4c43-a3ee-f90044744ab6.jpeg)

Set heading to "Settings"
![image](https://user-images.githubusercontent.com/458134/187073299-ec2f994b-c466-4357-a327-29d3668d5aa5.jpeg)

Set heading to "Licensing"
![image](https://user-images.githubusercontent.com/458134/187073339-b3a0cd26-a328-493b-91ad-abc8ed73d99d.jpeg)

**Comment by nataliebrotherton** [comment]
just to be clear, each heading should be the exact name of the settings submenus? so remove "WildApricot" from the settings and auth page headings?

**Comment by asirota** [comment]
Correct.
