### ISSUE TITLE
Post upload to WordPress SVN ensure update/auto-update functions work

### ISSUE THREAD

**Issue by asirota** [NewPath-Consulting/Wild-Apricot-Press#112]
Now that our plugin will be approved into the WordPress plugin repo under SVN we can check our  Update/Auto-Update feature.

Update feature: 

Auto Update available since WordPress 5.5 -> 

https://make.wordpress.org/core/2020/07/15/controlling-plugin-and-theme-auto-updates-ui-in-wordpress-5-5/

**Comment by nataliebrotherton** [comment]
so what is to be done here? it seems like if auto update is enabled/used by site admins it will happen when the svn repo is updated

**Comment by asirota** [comment]
What is unclear is what happens when the svn is updated. It isn't clear whether we need to do anything to enable updates in the code or if it happens on its own.

**Comment by asirota** [comment]
Also there is the normal update that an admin initiates and a separate auto update feature that can be enabled on wp 5.5 and later.

**Comment by nataliebrotherton** [comment]
>By default, WordPress itself is configured to automatically update when new minor versions become available.

I'm guessing mirror refers to the SVN repository hosted by WordPress?

>A number of hooks are included for plugin authors and WordPress developers to customize the new feature to fit their needs.

And it seems like the hooks are meant for developers to change the default behavior of the auto-updates.

**Comment by asirota** [comment]
When we have another update to 1.0.2 and update svn we will see how the UI changes in the installed plugins screen. I expect an update link to appear. 

Also note that the folder the WordPress team created is based on our official plugin slug `newpath-wildapricot` and as a result we may need to change our GitHub repo name. I don't think that will cause any issues except for direct links we have to it from our website which will need an update.

**Comment by nataliebrotherton** [comment]
>as a result we may need to change our GitHub repo name

fine by me

**Comment by asirota** [comment]
Auto update is enabled when an update is loaded via svn.
