### ISSUE TITLE
Deleting WAP plugin should remove connectivity and credential saved

### ISSUE THREAD

**Issue by RuthNP** [NewPath-Consulting/Wild-Apricot-Press#113]
Deleted WAP on trade association test site 
Upon reinstall - previous credentials and connectivity were already in place: 

- Valid WildApricot credentials have been saved.
- Your WordPress site has been connected to http://trade.newpathconsulting.com

Is this intended?

**Comment by asirota** [comment]
It is by default. There's an option to remove all wap settings on uninstall and delete you can check in wap settings. If you do that it clears everything out.
