### ISSUE TITLE
WordPress Licensing - Error: License is not 100% free as indicated

### ISSUE THREAD

**Issue by RuthNP** [NewPath-Consulting/Wild-Apricot-Press#114]
Enable WAP with your license key
Enter your license key(s) here. If you do not already have a license key, please visit our website [here](https://newpathconsulting.com/wap/) to get a license key. **The license key for WildApricot Press is 100% free,** and we never share your information with any third party.

**Comment by asirota** [comment]
@nataliebrotherton lets remove the 100% free sentence.
