### ISSUE TITLE
Check minimum Php version and required modules installed

### ISSUE THREAD

**Issue by asirota** [NewPath-Consulting/Wild-Apricot-Press#122]
Check if PHP is 7.4+ installedf first. 

Alsoo check if these modules need to be installed for WAP to function. If these are not available, show which ones need to be installed and exist "activate plugin" procedure

bcmath	7.4.33
bz2	7.4.33
calendar	7.4.33
cgi-fcgi	7.4.33
Core	7.4.33
ctype	7.4.33
curl	7.4.33
date	7.4.33
dba	7.4.33
dom	20031129
exif	7.4.33
fileinfo	7.4.33
filter	7.4.33
ftp	7.4.33
gd	7.4.33
gettext	7.4.33
gmp	7.4.33
hash	7.4.33
iconv	7.4.33
imap	7.4.33
intl	7.4.33
json	7.4.33
libxml	7.4.33
mbstring	7.4.33
mysqli	7.4.33
mysqlnd	7.4.33
openssl	7.4.33
pcre	7.4.33
PDO	7.4.33
pdo_mysql	7.4.33
pdo_sqlite	7.4.33
Phar	7.4.33
posix	7.4.33
Reflection	7.4.33
session	7.4.33
shmop	7.4.33
SimpleXML	7.4.33
soap	7.4.33
sodium	7.4.33
SPL	7.4.33
sqlite3	7.4.33
standard	7.4.33
tidy	7.4.33
tokenizer	7.4.33
xml	7.4.33
xmlreader	7.4.33
xmlwriter	7.4.33
xsl	7.4.33
Zend OPcache	7.4.33
zip	1.15.6
zlib	7.4.33

**Comment by mDisna** [comment]
I was able to determine that the required extensions are `mbstring`, `json`, and `filter`.

**Comment by asirota** [comment]
Here's what WordPress needs for PHP in terms of extensions:

https://make.wordpress.org/hosting/handbook/server-environment/#:~:text=The%20PHP%20extensions%20listed%20below%20are%20required%20for,mysqlnd%20%E2%80%93%20Connects%20to%20MySQL%20for%20database%20interactions.
