### ISSUE TITLE
Access control is not syncing with Group designation for user

### ISSUE THREAD

**Issue by Crednib** [NewPath-Consulting/Wild-Apricot-Press#135]
After testing that after login the user CarolBinder (Crednib@gmail.com) was created with the WA group field (Admin Test Team), the page 'Adult Classes' had the access control set that group Admin Test Team would be visible.  Note: The Account ID is not being added from WA to WP.

After logging in, and going to https://mpg.newpathconsulting.com/adult-classes/ the page is not visible and the message includes: 
<img width="960" alt="MPG WAP Access Control Screen Shot" src="https://user-images.githubusercontent.com/75815231/230207028-f9d2df38-2eae-4aa8-8578-4720b5f64829.png"

If the user is logged out and goes to the same page the message is: "This post is restricted to specific WildApricot users. Log into your WildApricot account or ask your administrator to add you to the post." which is correct.

Here is the error log from that session: 
[MPG Error Log from WA User setup to Page Access Control for Group.txt](https://github.com/NewPath-Consulting/Wild-Apricot-Press/files/11162975/MPG.Error.Log.from.WA.User.setup.to.Page.Access.Control.for.Group.txt)

**Comment by asirota** [comment]
Here's the video of the incorrect behaviour:

https://drive.google.com/file/d/1wj84lkyFzp2EVj1GAVsjXVr7UErmMrtO/view?usp=sharing
