### ISSUE TITLE
Update blueprint theme directive

### ISSUE THREAD

**Issue by nataliebrotherton** [NewPath-Consulting/Wild-Apricot-Press#178]
### I have checked the following:

- [X] I use the newest version of WildApricot Press.
- [X] I've searched existing issues and found nothing related to my issue.

### WildApricot Press version:

1.0.3

### Describe the bug

The current blueprint is using an outdated scheme for the theme directive.

### Screenshots/Live demo link

![image](https://github.com/user-attachments/assets/15ed4257-a869-4c97-b1f3-5996fbc0df38)

**Comment by asirota** [comment]
Fixed 

https://playground.wordpress.net/?blueprint-url=https%3A%2F%2Fraw.githubusercontent.com%2FNewPath-Consulting%2FWild-Apricot-Press%2Frefs%2Fheads%2F1.1%2Fassets%2Fblueprints%2Fblueprint.json

I added a commit to the 1.1 branch to fix this.
