### ISSUE TITLE
If all levels checked, should an additional feature be added so all logged in wa users can see content?

### ISSUE THREAD

**Issue by kendrakleber** [NewPath-Consulting/Wild-Apricot-Press#28]
When a site administrator checks all member level and group boxes, they generally intend for every logged in user with a wa membership to be able to see the content. However, in the case that a user is logged in to a wild apricot account but doesn't have any member levels or groups, they wouldn't be able to see content.

One intuitive way to solve this would be when all boxes are checked, all users with the appropriate membership status(es) (Active, Lapsed, etc) could view the content. This could cause an issue in the case that a group using wa has limited levels, such as "secret" and  "super secret", and they only give that to certain users, and the rest of the members are not assigned levels. However, this is an extremely unlikely use case, as most groups with this structure would also have a roll for "basic", and would expect all users to be able to see content if all boxes are checked.

Another, better (?) intuitive solution would be to add a checkbox under Wild Apricot Access Control, at the very top, above "Select All Membership Levels", for "All Members", and this would allow all members with the correct status as selected on the WA4WP Settings page (Active, PendingNew, etc)

**Comment by asirota** [comment]
In fact a contact without membership level assigned is not a member so they should NOT be able to see content restricted to all levels.
