### ISSUE TITLE
Custom Fields on Sync Options doesn't load on staging site

### ISSUE THREAD

**Issue by asirota** [NewPath-Consulting/Wild-Apricot-Press#42]
Custom Sync Options load fine on DEV
https://dev.newpathconsulting.com/wp-admin/admin.php?page=wawp-wal-admin&tab=fields

![image](https://user-images.githubusercontent.com/458134/134405533-1b45749e-f23f-427a-943b-9bfb5acec9f9.png)

On Bizbox (staging), WAP has been activated fine but the sync options don't load. Error:

Your Wild Apricot site does not have any contact fields!

is raised requiring authentication.

![image](https://user-images.githubusercontent.com/458134/134405699-3cf2e969-ff4a-453b-b972-9c00f033bdb9.png)

Authentication is complete, though.

![image](https://user-images.githubusercontent.com/458134/134405891-b8fd6221-c415-4bff-839f-98ca8a8e3a9f.png)

**Comment by krisXh** [comment]
I have the same issue on my current test site. 

Even though WAP correctly imports the fields: Account ID, Membership Level, User Status, Organization, Groups when creating the user. And neither the WAP Member Directory Add-on  nor the WAP Wild Apricot iFrame Add-on works - perhaps the same issue?

**Comment by asirota** [comment]
@krisXh please updated to the latest WAP version
