### ISSUE TITLE
Menu breaks page when WAP is activated

### ISSUE THREAD

**Issue by jackatnewpath** [NewPath-Consulting/Wild-Apricot-Press#46]
Received this error after activating WAP on a client site. Site details and login info sent in an email.

[14-Oct-2021 18:59:23 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function WAWP\mb_convert_encoding() in /home/ohanahc/public_html/wp-content/plugins/Wild-Apricot-Press/src/WAIntegration.php:1180
Stack trace:
#0 /home/ohanahc/public_html/wp-includes/class-wp-hook.php(303): WAWP\WAIntegration->create_wa_login_logout('<li id="menu-it...', Object(stdClass))
#1 /home/ohanahc/public_html/wp-includes/plugin.php(189): WP_Hook->apply_filters('<li id="menu-it...', Array)
#2 /home/ohanahc/public_html/wp-includes/nav-menu-template.php(259): apply_filters('wp_nav_menu_ite...', '<li id="menu-it...', Object(stdClass))
#3 /home/ohanahc/public_html/wp-content/plugins/gp-premium/menu-plus/functions/generate-menu-plus.php(1059): wp_nav_menu(Object(stdClass))
#4 /home/ohanahc/public_html/wp-includes/class-wp-hook.php(303): generate_menu_plus_mobile_header('')
#5 /home/ohanahc/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#6 /home/ohanahc/public_html/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#7 /home/ohanahc/pub in /home/ohanahc/public_html/wp-content/plugins/Wild-Apricot-Press/src/WAIntegration.php on line 1180

The attached image show a before and after and shows where the page breaks.

This behavior only happens when WAP is activated.
The theme in use is Generate Press Premium

**Comment by jackatnewpath** [comment]
<img width="1817" alt="ohana menu crashes when WAP Login added to main menu" src="https://user-images.githubusercontent.com/89658802/137808567-d18cd592-30e4-4415-82eb-8e0af10bedaa.PNG">

**Comment by asirota** [comment]
@1cookspe do you think you can look into this?

**Comment by Crednib** [comment]
@1cookspe Hello and we all hope you are doing well! I added you to the Ohana WordPress site (as an administrator) last week and you should have received an email with login info. @jackatnewpath and I have been looking at this too so if you need us to hop on a call just let me know (email or slack).  It appears that when we activate the WAP the screen will go blank (except for the logo on the header).  As always, thank you for your help and expertise!
