### ISSUE TITLE
Show menus based on access control

### ISSUE THREAD

**Issue by asirota** [NewPath-Consulting/Wild-Apricot-Press#48]
The menu system in WordPress currently doesn't look at access Control on a page. 

Use cases

A) check access control for a page or post in a menu 

B) if current logged in user does not have access to page or post hide the menu item from the menu. 

This feature should  be a WAP setting as not everyone wants to show / hide menu items based on access control. For some admins showing the menu would be ok, and the restricted message would encourage upgrading for access controlled  content.

**Comment by krisXh** [comment]
Alex, I'm not sure this is right. Menu items that are pages under WAP access control are disappearing for me when I'm not logged in!

**Comment by asirota** [comment]
Terrific I wondered about this. We did look into the menu system now that I recall. I'll close this.
