### ISSUE TITLE
Compatibility with the Avada builder and theme

### ISSUE THREAD

**Issue by asirota** [NewPath-Consulting/Wild-Apricot-Press#54]
When using the [Avada theme and Avada Builder](https://avada.theme-fusion.com/), the WAP plugin doesn't add the login/logout menu to the configured menus. It appears Avada modifies the menu manager in some way that is not support by our plugin. No errors are thrown but the menu is not being modified.

On dev.newpathconsulting.com, the Avada theme and related plugins have been loaded. The WAP configuration has both menus configured but the login link doesn't appear in the main menu:

![image](https://user-images.githubusercontent.com/458134/154363192-5a5ad209-7e72-46aa-a73b-18bc028315bb.png)

Note absence of the Login menu

![image](https://user-images.githubusercontent.com/458134/154363253-506edd52-3d4d-45d3-92e9-9764141f52c2.png)

**Comment by asirota** [comment]
@1cookspe can you add some comments on the fix here?

**Comment by 1cookspe** [comment]
We found that Avada's menu did not have a `theme_location` parameter, so our current code did not add the Login/Logout button to the menu. Now, the Login/Logout button is added if `theme_location` is empty.

**Comment by asirota** [comment]
closing this as it was fixed in b2
