### ISSUE TITLE
cosmetic naming touches for 1.0b4

### ISSUE THREAD

**Issue by asirota** [NewPath-Consulting/Wild-Apricot-Press#74]
A few small items before we push out 1.0b4

1. plugin name: NewPath Wild Apricot Press (WAP) -> should be called **WildApricot Press (WAP)**

Note no space between Wild and APricot

2. description should be: **Integrates your WildApricot-powered organization with a WordPress website! Powered by WildApricot's API.**

3. Some UI label changes Wild Apricot -> WildApricot

![image](https://user-images.githubusercontent.com/458134/181368596-3995e0ec-4e90-44f1-ae73-703b29aed197.png)

![image](https://user-images.githubusercontent.com/458134/181368756-c645dad9-b651-42fd-8e45-a0405bdc4752.png)

![image](https://user-images.githubusercontent.com/458134/181369021-51ce8a42-86d2-471f-83c2-16931fff7577.png)

**Comment by asirota** [comment]
On the page/post editor - access control metabox

![image](https://user-images.githubusercontent.com/458134/181369229-29efc8d5-e724-4ef3-9735-84c312170852.png)

**Comment by asirota** [comment]
On the individual restriction message

![image](https://user-images.githubusercontent.com/458134/181369354-1fc3e727-a9f3-40ec-9a3a-bdb482a27f49.png)

**Comment by nataliebrotherton** [comment]
should the wildapricot licensed urls/account ids columns in the license key database be changed as well for consistency?
<img width="409" alt="Screen Shot 2022-08-01 at 3 31 33 PM" src="https://user-images.githubusercontent.com/25440470/182230464-074cc200-2893-499a-893f-338863954a16.png">

**Comment by asirota** [comment]
> should the wildapricot licensed urls/account ids columns in the license key database be changed as well for consistency?

I could change the underlying data structure labels in Make but I am not sure of the dependency and how that would affect the underlying scenarios that use the datastore. I suppose I could test this on our development license checker to see if it makes a difference. And also the license key generator too since they put data into the data store too.

**Comment by asirota** [comment]
Changing the underlying data structure wipes out the original data in the data store, so I would need to export the data out of data store, change the structure and then reimport the data manually or with a scenario, and then retest the license key checker and the license key generator to make sure they are working with the new data structure name. I don't think it's worth the time for something internal like this.
