### ISSUE TITLE
Modify Plugin Options to add an option to delete all WAP related database options

### ISSUE THREAD

**Issue by asirota** [NewPath-Consulting/Wild-Apricot-Press#95]
add a new checkbox to remove all WAP related database options in the wp_options table

Label it "Delete all WildApricot Press settings in WordPress database"

**Comment by nataliebrotherton** [comment]
Just to clarify, the existing setting "Delete all WildApricot Press settings from WordPress database" should both delete all WAP DB data AND the WA user metadata? It currently just deletes the user metadata.

**Comment by nataliebrotherton** [comment]
And then if neither of the deletion options are checked, the plugin shouldn't delete any WAP or WA data from the site?

**Comment by asirota** [comment]
> Just to clarify, the existing setting "Delete all WildApricot Press settings from WordPress database" should both delete all WAP DB data AND the WA user metadata? It currently just deletes the user metadata.

No keep that doing what it does. The label should say "Delete all WildApricot users added by WildApricot Press from WordPress database"

**Comment by asirota** [comment]
> And then if neither of the deletion options are checked, the plugin shouldn't delete any WAP or WA data from the site?

Correct, this is the default state on install.

**Comment by nataliebrotherton** [comment]
And should the DB or user option delete the WAP login page? Maybe the user option?

**Comment by asirota** [comment]
> And should the DB or user option delete the WAP login page? Maybe the user option?

when the plugin is deactivated that's when the login page is deleted. When activated the login page is created as far as I understand.

There may be other auxiliary pages we create eventually with the theme so let's make it easy to add other pages to be deleted/created this way.

**Comment by nataliebrotherton** [comment]
Ok. And what about the WAP post meta?

**Comment by asirota** [comment]
> Ok. And what about the WAP post meta?

good point that should be the new option called "Delete all WildApricot Press related database options. This will delete all WildApricot Press licenses, authorization keys, page and  post metadata like access restrictions, sync field options."

**Comment by nataliebrotherton** [comment]
New description on deletion seettings

<img width="1006" alt="Screen Shot 2022-08-16 at 4 06 57 PM" src="https://user-images.githubusercontent.com/25440470/184974904-4784a7c9-f993-4e86-9bb0-9558de552f1a.png">

**Comment by asirota** [comment]
I wouldn't specify "first" or "second" box since the UI may be altered on certain devices.

**Comment by nataliebrotherton** [comment]
Should the DB option also delete the logfile? Or should that be a separate option?

**Comment by asirota** [comment]
> Should the DB option also delete the logfile? Or should that be a separate option?

Yes on deletion the logfile should be removed as well.

**Comment by nataliebrotherton** [comment]
And the plugin should delete the block plugins as well? Despite what the deletion options are?

**Comment by nataliebrotherton** [comment]
> And the plugin should delete the block plugins as well? Despite what the deletion options are?

@asirota

**Comment by asirota** [comment]
No the deletion on wap should not Delete then block plugins. Are there any options for those ?
